# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format
# Try to maintain entries sorted alphabetically inside each "group".
[versions]
flyway = "11.18.0"
googleJavaFormat = "1.32.0"
h2 = "2.4.240"
junit-jupiter = "6.0.1"
ktlint = "1.8.0"

[libraries]
errorprone = "com.google.errorprone:error_prone_core:2.45.0"
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
nullaway = "com.uber.nullaway:nullaway:0.12.12"
truth = "com.google.truth:truth:1.4.5"

# Versions used in build script, libraries added here for Dependabot
googleJavaFormat = { module = "com.google.googlejavaformat:google-java-format", version.ref = "googleJavaFormat" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref="junit-jupiter" }
ktlint = { module = "com.pinterest.ktlint:ktlint-cli", version.ref = "ktlint" }

[bundles]

[plugins]
errorprone = "net.ltgt.errorprone:4.3.0"
gradlePluginPublish = "com.gradle.plugin-publish:2.0.0"
nullaway = "net.ltgt.nullaway:2.3.0"
spotless = "com.diffplug.spotless:8.1.0"
